/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -i mabstractappinterface.h -a mdecorator_dbus_adaptor.h: mdecorator_dbus.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef MDECORATOR_DBUS_ADAPTOR_H_1364764193
#define MDECORATOR_DBUS_ADAPTOR_H_1364764193

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "mabstractappinterface.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.nokia.MDecorator
 */
class MDecoratorAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.nokia.MDecorator")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.nokia.MDecorator\">\n"
"    <method name=\"setActions\">\n"
"      <arg direction=\"in\" type=\"a(ssbbuay)\" name=\"actions\"/>\n"
"      <annotation value=\"MDecoratorIPCActionList\" name=\"com.trolltech.QtDBus.QtTypeName.In0\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"window\"/>\n"
"    </method>\n"
"    <signal name=\"triggered\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"uuid\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"checked\"/>\n"
"    </signal>\n"
"    <signal name=\"toggled\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"uuid\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"checked\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    MDecoratorAdaptor(QObject *parent);
    virtual ~MDecoratorAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void setActions(MDecoratorIPCActionList actions, uint window);
Q_SIGNALS: // SIGNALS
    void toggled(const QString &uuid, bool checked);
    void triggered(const QString &uuid, bool checked);
};

#endif
