/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -i mabstractappinterface.h -c MDecoratorInterface -i mdecorator_dbus_interface.h -p :mdecorator_dbus_interface.cpp mdecorator_dbus.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "mabstractappinterface.h"
#include "mdecorator_dbus_interface.h"
/*
 * Implementation of interface class MDecoratorInterface
 */

MDecoratorInterface::MDecoratorInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

MDecoratorInterface::~MDecoratorInterface()
{
}

