/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -i mabstractappinterface.h -i mdecorator_dbus_adaptor.h -a :mdecorator_dbus_adaptor.cpp mdecorator_dbus.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "mabstractappinterface.h"
#include "mdecorator_dbus_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class MDecoratorAdaptor
 */

MDecoratorAdaptor::MDecoratorAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

MDecoratorAdaptor::~MDecoratorAdaptor()
{
    // destructor
}

void MDecoratorAdaptor::setActions(MDecoratorIPCActionList actions, uint window)
{
    // handle method call com.nokia.MDecorator.setActions
    QMetaObject::invokeMethod(parent(), "setActions", Q_ARG(MDecoratorIPCActionList, actions), Q_ARG(uint, window));
}

